spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-plus

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug